# Generated by Django 4.0.3 on 2023-07-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='country_information_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, choices=[['Spain', 'Spain'], ['France', 'France'], ['Italy', 'Italy'], ['Slovenia', 'Slovenia'], ['Croatia', 'Croatia'], ['Bosnia and Herzegovina', 'Bosnia and Herzegovina'], ['Montenegro', 'Montenegro'], ['Albania', 'Albania'], ['Kosovo', 'Kosovo'], ['Greece', 'Greece'], ['Hungary', 'Hungary'], ['Romania', 'Romania'], ['Serbia', 'Serbia'], ['Bulgaria', 'Bulgaria'], ['Turkey', 'Turkey'], ['Iran', 'Iran'], ['Georgia', 'Georgia'], ['Armenia', 'Armenia'], ['Azerbaijan', 'Azerbaijan'], ['Russia', 'Russia'], ['Kazakhstan', 'Kazakhstan'], ['Turkmenistan', 'Turkmenistan'], ['Uzbekistan', 'Uzbekistan'], ['Tajikistan', 'Tajikistan'], ['Kyrgyzstan', 'Kyrgyzstan'], ['Pakistan', 'Pakistan'], ['India', 'India'], ['Nepal', 'Nepal'], ['Bangladesh', 'Bangladesh'], ['Myanmar', 'Myanmar'], ['Thailand', 'Thailand'], ['Laos', 'Laos'], ['Vietnam', 'Vietnam'], ['China', 'China'], ['South Korea', 'South Korea'], ['Japan', 'Japan'], ['United States', 'United States'], ['', ''], ['', ''], ['', '']], max_length=33, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('rent_per_capita', models.IntegerField(blank=True, null=True)),
                ('surface', models.IntegerField(blank=True, null=True)),
                ('regime', models.CharField(blank=True, choices=[['Spain', 'Spain'], ['France', 'France'], ['Italy', 'Italy'], ['Slovenia', 'Slovenia'], ['Croatia', 'Croatia'], ['Bosnia and Herzegovina', 'Bosnia and Herzegovina'], ['Montenegro', 'Montenegro'], ['Albania', 'Albania'], ['Kosovo', 'Kosovo'], ['Greece', 'Greece'], ['Hungary', 'Hungary'], ['Romania', 'Romania'], ['Serbia', 'Serbia'], ['Bulgaria', 'Bulgaria'], ['Turkey', 'Turkey'], ['Iran', 'Iran'], ['Georgia', 'Georgia'], ['Armenia', 'Armenia'], ['Azerbaijan', 'Azerbaijan'], ['Russia', 'Russia'], ['Kazakhstan', 'Kazakhstan'], ['Turkmenistan', 'Turkmenistan'], ['Uzbekistan', 'Uzbekistan'], ['Tajikistan', 'Tajikistan'], ['Kyrgyzstan', 'Kyrgyzstan'], ['Pakistan', 'Pakistan'], ['India', 'India'], ['Nepal', 'Nepal'], ['Bangladesh', 'Bangladesh'], ['Myanmar', 'Myanmar'], ['Thailand', 'Thailand'], ['Laos', 'Laos'], ['Vietnam', 'Vietnam'], ['China', 'China'], ['South Korea', 'South Korea'], ['Japan', 'Japan'], ['United States', 'United States'], ['', ''], ['', ''], ['', '']], max_length=33, null=True)),
                ('currency', models.CharField(blank=True, choices=[['Spain', 'Spain'], ['France', 'France'], ['Italy', 'Italy'], ['Slovenia', 'Slovenia'], ['Croatia', 'Croatia'], ['Bosnia and Herzegovina', 'Bosnia and Herzegovina'], ['Montenegro', 'Montenegro'], ['Albania', 'Albania'], ['Kosovo', 'Kosovo'], ['Greece', 'Greece'], ['Hungary', 'Hungary'], ['Romania', 'Romania'], ['Serbia', 'Serbia'], ['Bulgaria', 'Bulgaria'], ['Turkey', 'Turkey'], ['Iran', 'Iran'], ['Georgia', 'Georgia'], ['Armenia', 'Armenia'], ['Azerbaijan', 'Azerbaijan'], ['Russia', 'Russia'], ['Kazakhstan', 'Kazakhstan'], ['Turkmenistan', 'Turkmenistan'], ['Uzbekistan', 'Uzbekistan'], ['Tajikistan', 'Tajikistan'], ['Kyrgyzstan', 'Kyrgyzstan'], ['Pakistan', 'Pakistan'], ['India', 'India'], ['Nepal', 'Nepal'], ['Bangladesh', 'Bangladesh'], ['Myanmar', 'Myanmar'], ['Thailand', 'Thailand'], ['Laos', 'Laos'], ['Vietnam', 'Vietnam'], ['China', 'China'], ['South Korea', 'South Korea'], ['Japan', 'Japan'], ['United States', 'United States'], ['', ''], ['', ''], ['', '']], max_length=33, null=True)),
                ('local_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='summary_day_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_day_model', models.IntegerField(default=16, null=True)),
                ('country', models.CharField(blank=True, choices=[['Spain', 'Spain'], ['France', 'France'], ['Italy', 'Italy'], ['Slovenia', 'Slovenia'], ['Croatia', 'Croatia'], ['Bosnia and Herzegovina', 'Bosnia and Herzegovina'], ['Montenegro', 'Montenegro'], ['Albania', 'Albania'], ['Kosovo', 'Kosovo'], ['Greece', 'Greece'], ['Hungary', 'Hungary'], ['Romania', 'Romania'], ['Serbia', 'Serbia'], ['Bulgaria', 'Bulgaria'], ['Turkey', 'Turkey'], ['Iran', 'Iran'], ['Georgia', 'Georgia'], ['Armenia', 'Armenia'], ['Azerbaijan', 'Azerbaijan'], ['Russia', 'Russia'], ['Kazakhstan', 'Kazakhstan'], ['Turkmenistan', 'Turkmenistan'], ['Uzbekistan', 'Uzbekistan'], ['Tajikistan', 'Tajikistan'], ['Kyrgyzstan', 'Kyrgyzstan'], ['Pakistan', 'Pakistan'], ['India', 'India'], ['Nepal', 'Nepal'], ['Bangladesh', 'Bangladesh'], ['Myanmar', 'Myanmar'], ['Thailand', 'Thailand'], ['Laos', 'Laos'], ['Vietnam', 'Vietnam'], ['China', 'China'], ['South Korea', 'South Korea'], ['Japan', 'Japan'], ['United States', 'United States'], ['', ''], ['', ''], ['', '']], max_length=33, null=True)),
                ('day_type', models.CharField(blank=True, choices=[('resting', 'resting'), ('cycling', 'cycling')], max_length=33, null=True)),
                ('night_type', models.CharField(blank=True, choices=[('outside', 'outside'), ('accommodation', 'accommodation')], max_length=33, null=True)),
                ('money_supermarket', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('money_restaurant', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('money_accommodation', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('money_equipment', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('money_transport', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('money_burocracy', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('money_others', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('km_first_stop', models.IntegerField(blank=True, null=True)),
                ('km_second_stop', models.IntegerField(blank=True, null=True)),
                ('km_third_stop', models.IntegerField(blank=True, null=True)),
                ('km_fourth_stop', models.IntegerField(blank=True, null=True)),
                ('altitude_first_stop', models.IntegerField(blank=True, null=True)),
                ('altitude_second_stop', models.IntegerField(blank=True, null=True)),
                ('altitude_third_stop', models.IntegerField(blank=True, null=True)),
                ('altitude_fourth_stop', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
