# Generated by Django 4.0.3 on 2023-11-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicleteiros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='km_altitude_model',
            name='journey_day',
            field=models.IntegerField(default=55, null=True),
        ),
        migrations.AlterField(
            model_name='money_model',
            name='journey_day',
            field=models.IntegerField(default=55, null=True),
        ),
    ]
