# Generated by Django 4.0.3 on 2023-10-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicleteiros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos_model',
            name='week',
            field=models.CharField(default='Pon a semana', max_length=1000),
        ),
        migrations.AlterField(
            model_name='videos_model',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
