# Generated by Django 4.0.3 on 2023-07-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicleteiros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country_information_model',
            name='regime',
        ),
        migrations.AddField(
            model_name='country_information_model',
            name='capital_town',
            field=models.CharField(blank=True, max_length=33, null=True),
        ),
        migrations.AlterField(
            model_name='summary_day_model',
            name='journey_day_model',
            field=models.IntegerField(default=18, null=True),
        ),
    ]
