# Generated by Django 4.0.3 on 2023-12-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicleteiros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='km_altitude_model',
            options={'ordering': ['-journey_day']},
        ),
        migrations.AlterModelOptions(
            name='money_model',
            options={'ordering': ['-journey_day']},
        ),
        migrations.AlterField(
            model_name='km_altitude_model',
            name='journey_day',
            field=models.IntegerField(default=74, null=True),
        ),
        migrations.AlterField(
            model_name='money_model',
            name='journey_day',
            field=models.IntegerField(default=74, null=True),
        ),
    ]
