# Generated by Django 4.0.3 on 2023-11-08 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bicicleteiros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[['Euro', 'Euro'], ['Lek - Albania', 'Lek - Albania'], ['Forint - Hungary', 'Forint - Hungary'], ['Romanian Leu - Romania', 'Romanian Leu - Romania'], ['Serbian Dinar - Serbia', 'Serbian Dinar - Serbia'], ['Bulgaria Lev - Bulgaria', 'Bulgaria Lev - Bulgaria'], ['Turkey Lira - Turkey', 'Turkey Lira - Turkey'], ['Iran Rial - Iran', 'Iran Rial - Iran'], ['Georgian lari - Georgia', 'Georgian lari - Georgia'], ['Armenian dram - Armenia', 'Armenian dram - Armenia'], ['Azerbaijani manat - Azerbaijan', 'Azerbaijani manat - Azerbaijan'], ['Russian ruble - Russia', 'Russian ruble - Russia'], ['Kazakhstani tenge - Kazakhstan', 'Kazakhstani tenge - Kazakhstan'], ['Turkmenistani manat - Turkmenistan', 'Turkmenistani manat - Turkmenistan'], ['Uzbekistani sum - Uzbekistan', 'Uzbekistani sum - Uzbekistan'], ['Tajikistani somoni - Tajikistan', 'Tajikistani somoni - Tajikistan'], ['Kyrgyz som - Kyrgyzstan', 'Kyrgyz som - Kyrgyzstan'], ['Pakistani rupee - Pakistan', 'Pakistani rupee - Pakistan'], ['Indian rupee - India', 'Indian rupee - India'], ['Nepalese rupee - Nepal', 'Nepalese rupee - Nepal'], ['Bangladeshi taka - Bangladesh', 'Bangladeshi taka - Bangladesh'], ['Burmese kyat - Myanmar', 'Burmese kyat - Myanmar'], ['Thai baht - Thailand', 'Thai baht - Thailand'], ['Lao kip - Laos', 'Lao kip - Laos'], ['Vietnamese dong - Vietnam', 'Vietnamese dong - Vietnam'], ['Renminbi - China', 'Renminbi - China'], ['South Korean won - South Korea', 'South Korean won - South Korea'], ['Japanese yen - Japan', 'Japanese yen - Japan'], ['United States dollar - US', 'United States dollar - US']], max_length=50)),
                ('currency_change_euro', models.DecimalField(decimal_places=5, max_digits=15)),
            ],
        ),
        migrations.AlterModelOptions(
            name='chat_comments_replies_model',
            options={'ordering': ['-date_added']},
        ),
        migrations.RemoveField(
            model_name='country_information_model',
            name='currency_change_euro',
        ),
        migrations.AlterField(
            model_name='chat_comments_model',
            name='number_of_replies',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='chat_comments_model',
            name='username_comment',
            field=models.CharField(blank=True, default='paquinho89', max_length=33, null=True),
        ),
        migrations.AlterField(
            model_name='chat_comments_replies_model',
            name='reply_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='km_altitude_model',
            name='journey_day',
            field=models.IntegerField(default=39, null=True),
        ),
        migrations.AlterField(
            model_name='km_altitude_model',
            name='week',
            field=models.IntegerField(default=6, null=True),
        ),
        migrations.AlterField(
            model_name='money_model',
            name='journey_day',
            field=models.IntegerField(default=39, null=True),
        ),
        migrations.AlterField(
            model_name='money_model',
            name='week',
            field=models.IntegerField(default=6, null=True),
        ),
        migrations.AlterField(
            model_name='videos_model',
            name='week',
            field=models.IntegerField(default=6, null=True),
        ),
        migrations.AlterField(
            model_name='country_information_model',
            name='currency',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.PROTECT, to='bicicleteiros.currency'),
            preserve_default=False,
        ),
    ]
