# Generated by Django 4.0.3 on 2023-10-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicleteiros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='km_altitude_model',
            name='week',
            field=models.IntegerField(default=4, null=True),
        ),
        migrations.AlterField(
            model_name='km_altitude_model',
            name='journey_day',
            field=models.IntegerField(default=25, null=True),
        ),
        migrations.AlterField(
            model_name='money_model',
            name='journey_day',
            field=models.IntegerField(default=25, null=True),
        ),
        migrations.AlterField(
            model_name='videos_model',
            name='week',
            field=models.IntegerField(default=4, null=True),
        ),
    ]
