# Generated by Django 4.0.3 on 2023-10-23 21:46

import bicicleteiros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicleteiros', '0002_videos_model_week_alter_videos_model_youtube_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='photos_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, choices=[['Spain', 'Spain'], ['France', 'France'], ['Italy', 'Italy'], ['Slovenia', 'Slovenia'], ['Croatia', 'Croatia'], ['Bosnia and Herzegovina', 'Bosnia and Herzegovina'], ['Montenegro', 'Montenegro'], ['Albania', 'Albania'], ['Greece', 'Greece'], ['Hungary', 'Hungary'], ['Romania', 'Romania'], ['Serbia', 'Serbia'], ['Bulgaria', 'Bulgaria'], ['Turkey', 'Turkey'], ['Iran', 'Iran'], ['Georgia', 'Georgia'], ['Armenia', 'Armenia'], ['Azerbaijan', 'Azerbaijan'], ['Russia', 'Russia'], ['Kazakhstan', 'Kazakhstan'], ['Turkmenistan', 'Turkmenistan'], ['Uzbekistan', 'Uzbekistan'], ['Tajikistan', 'Tajikistan'], ['Kyrgyzstan', 'Kyrgyzstan'], ['Pakistan', 'Pakistan'], ['India', 'India'], ['Nepal', 'Nepal'], ['Bangladesh', 'Bangladesh'], ['Myanmar', 'Myanmar'], ['Thailand', 'Thailand'], ['Laos', 'Laos'], ['Vietnam', 'Vietnam'], ['China', 'China'], ['South Korea', 'South Korea'], ['Japan', 'Japan'], ['United States', 'United States']], max_length=33, null=True, unique=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to=bicicleteiros.models.upload_image_path, verbose_name='TerraMeiga_picture')),
            ],
        ),
        migrations.AlterField(
            model_name='videos_model',
            name='week',
            field=models.IntegerField(),
        ),
    ]
