# Generated by Django 4.0.3 on 2023-07-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicleteiros', '0002_remove_country_information_model_regime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country_information_model',
            name='population_density',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
