# Generated by Django 4.0.3 on 2024-01-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicleteiros', '0002_alter_km_altitude_model_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='km_altitude_model',
            name='journey_day',
            field=models.IntegerField(default=-265, null=True),
        ),
        migrations.AlterField(
            model_name='km_altitude_model',
            name='week',
            field=models.IntegerField(default=-37, null=True),
        ),
        migrations.AlterField(
            model_name='money_model',
            name='journey_day',
            field=models.IntegerField(default=-265, null=True),
        ),
        migrations.AlterField(
            model_name='money_model',
            name='week',
            field=models.IntegerField(default=-37, null=True),
        ),
        migrations.AlterField(
            model_name='videos_model',
            name='week',
            field=models.IntegerField(default=-37, null=True),
        ),
    ]
