# Generated by Django 4.0.3 on 2023-07-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicleteiros', '0003_country_information_model_population_density'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country_information_model',
            name='local_time',
        ),
        migrations.AddField(
            model_name='country_information_model',
            name='time_zone',
            field=models.CharField(blank=True, max_length=33, null=True),
        ),
    ]
