# Generated by Django 4.0.3 on 2024-01-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicleteiros', '0004_alter_country_information_model_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='km_altitude_model',
            name='journey_day',
            field=models.IntegerField(default=23, null=True),
        ),
        migrations.AlterField(
            model_name='money_model',
            name='journey_day',
            field=models.IntegerField(default=23, null=True),
        ),
    ]
