# Generated by Django 4.0.3 on 2023-07-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicleteiros', '0004_remove_country_information_model_local_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country_information_model',
            name='time_zone',
            field=models.CharField(blank=True, choices=[], max_length=33, null=True),
        ),
    ]
