# Generated by Django 4.0.3 on 2023-07-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicleteiros', '0005_alter_country_information_model_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country_information_model',
            name='time_zone',
            field=models.CharField(blank=True, choices=[['Spain', 'Spain'], ['France', 'France'], ['Italy', 'Italy'], ['Slovenia', 'Slovenia'], ['Croatia', 'Croatia'], ['Bosnia and Herzegovina', 'Bosnia and Herzegovina'], ['Montenegro', 'Montenegro'], ['Albania', 'Albania'], ['Kosovo', 'Kosovo'], ['Greece', 'Greece'], ['Hungary', 'Hungary'], ['Romania', 'Romania'], ['Serbia', 'Serbia'], ['Bulgaria', 'Bulgaria'], ['Turkey', 'Turkey'], ['Iran', 'Iran'], ['Georgia', 'Georgia'], ['Armenia', 'Armenia'], ['Azerbaijan', 'Azerbaijan'], ['Russia', 'Russia'], ['Kazakhstan', 'Kazakhstan'], ['Turkmenistan', 'Turkmenistan'], ['Uzbekistan', 'Uzbekistan'], ['Tajikistan', 'Tajikistan'], ['Kyrgyzstan', 'Kyrgyzstan'], ['Pakistan', 'Pakistan'], ['India', 'India'], ['Nepal', 'Nepal'], ['Bangladesh', 'Bangladesh'], ['Myanmar', 'Myanmar'], ['Thailand', 'Thailand'], ['Laos', 'Laos'], ['Vietnam', 'Vietnam'], ['China', 'China'], ['South Korea', 'South Korea'], ['Japan', 'Japan'], ['United States', 'United States'], ['', ''], ['', ''], ['', '']], max_length=33, null=True),
        ),
    ]
