# Generated by Django 4.0.3 on 2023-07-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicleteiros', '0007_country_information_model_visa_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary_day_model',
            old_name='altitude_first_stop',
            new_name='altitude_day',
        ),
        migrations.RenameField(
            model_name='summary_day_model',
            old_name='km_first_stop',
            new_name='km_day',
        ),
        migrations.RemoveField(
            model_name='summary_day_model',
            name='altitude_fourth_stop',
        ),
        migrations.RemoveField(
            model_name='summary_day_model',
            name='altitude_second_stop',
        ),
        migrations.RemoveField(
            model_name='summary_day_model',
            name='altitude_third_stop',
        ),
        migrations.RemoveField(
            model_name='summary_day_model',
            name='km_fourth_stop',
        ),
        migrations.RemoveField(
            model_name='summary_day_model',
            name='km_second_stop',
        ),
        migrations.RemoveField(
            model_name='summary_day_model',
            name='km_third_stop',
        ),
        migrations.AlterField(
            model_name='country_information_model',
            name='country',
            field=models.CharField(blank=True, choices=[['Spain', 'Spain'], ['France', 'France'], ['Italy', 'Italy'], ['Slovenia', 'Slovenia'], ['Croatia', 'Croatia'], ['Bosnia and Herzegovina', 'Bosnia and Herzegovina'], ['Montenegro', 'Montenegro'], ['Albania', 'Albania'], ['Greece', 'Greece'], ['Hungary', 'Hungary'], ['Romania', 'Romania'], ['Serbia', 'Serbia'], ['Bulgaria', 'Bulgaria'], ['Turkey', 'Turkey'], ['Iran', 'Iran'], ['Georgia', 'Georgia'], ['Armenia', 'Armenia'], ['Azerbaijan', 'Azerbaijan'], ['Russia', 'Russia'], ['Kazakhstan', 'Kazakhstan'], ['Turkmenistan', 'Turkmenistan'], ['Uzbekistan', 'Uzbekistan'], ['Tajikistan', 'Tajikistan'], ['Kyrgyzstan', 'Kyrgyzstan'], ['Pakistan', 'Pakistan'], ['India', 'India'], ['Nepal', 'Nepal'], ['Bangladesh', 'Bangladesh'], ['Myanmar', 'Myanmar'], ['Thailand', 'Thailand'], ['Laos', 'Laos'], ['Vietnam', 'Vietnam'], ['China', 'China'], ['South Korea', 'South Korea'], ['Japan', 'Japan'], ['United States', 'United States']], max_length=33, null=True),
        ),
        migrations.AlterField(
            model_name='country_information_model',
            name='currency',
            field=models.CharField(blank=True, choices=[['Spain', 'Spain'], ['France', 'France'], ['Italy', 'Italy'], ['Slovenia', 'Slovenia'], ['Croatia', 'Croatia'], ['Bosnia and Herzegovina', 'Bosnia and Herzegovina'], ['Montenegro', 'Montenegro'], ['Albania', 'Albania'], ['Greece', 'Greece'], ['Hungary', 'Hungary'], ['Romania', 'Romania'], ['Serbia', 'Serbia'], ['Bulgaria', 'Bulgaria'], ['Turkey', 'Turkey'], ['Iran', 'Iran'], ['Georgia', 'Georgia'], ['Armenia', 'Armenia'], ['Azerbaijan', 'Azerbaijan'], ['Russia', 'Russia'], ['Kazakhstan', 'Kazakhstan'], ['Turkmenistan', 'Turkmenistan'], ['Uzbekistan', 'Uzbekistan'], ['Tajikistan', 'Tajikistan'], ['Kyrgyzstan', 'Kyrgyzstan'], ['Pakistan', 'Pakistan'], ['India', 'India'], ['Nepal', 'Nepal'], ['Bangladesh', 'Bangladesh'], ['Myanmar', 'Myanmar'], ['Thailand', 'Thailand'], ['Laos', 'Laos'], ['Vietnam', 'Vietnam'], ['China', 'China'], ['South Korea', 'South Korea'], ['Japan', 'Japan'], ['United States', 'United States']], max_length=33, null=True),
        ),
        migrations.AlterField(
            model_name='summary_day_model',
            name='country',
            field=models.CharField(blank=True, choices=[['Spain', 'Spain'], ['France', 'France'], ['Italy', 'Italy'], ['Slovenia', 'Slovenia'], ['Croatia', 'Croatia'], ['Bosnia and Herzegovina', 'Bosnia and Herzegovina'], ['Montenegro', 'Montenegro'], ['Albania', 'Albania'], ['Greece', 'Greece'], ['Hungary', 'Hungary'], ['Romania', 'Romania'], ['Serbia', 'Serbia'], ['Bulgaria', 'Bulgaria'], ['Turkey', 'Turkey'], ['Iran', 'Iran'], ['Georgia', 'Georgia'], ['Armenia', 'Armenia'], ['Azerbaijan', 'Azerbaijan'], ['Russia', 'Russia'], ['Kazakhstan', 'Kazakhstan'], ['Turkmenistan', 'Turkmenistan'], ['Uzbekistan', 'Uzbekistan'], ['Tajikistan', 'Tajikistan'], ['Kyrgyzstan', 'Kyrgyzstan'], ['Pakistan', 'Pakistan'], ['India', 'India'], ['Nepal', 'Nepal'], ['Bangladesh', 'Bangladesh'], ['Myanmar', 'Myanmar'], ['Thailand', 'Thailand'], ['Laos', 'Laos'], ['Vietnam', 'Vietnam'], ['China', 'China'], ['South Korea', 'South Korea'], ['Japan', 'Japan'], ['United States', 'United States']], max_length=33, null=True),
        ),
        migrations.AlterField(
            model_name='summary_day_model',
            name='journey_day_model',
            field=models.IntegerField(default=20, null=True),
        ),
    ]
