[phases.setup]
nixPkgs = ["openssl", "postgresql", "gcc","python310", "python310Packages.pip"]

[phases.build]
cmd = "python manage.py migrate"

[phases.start]
cmd = "gunicorn myproject.wsgi:application"
