# Generated by Django 4.0.3 on 2024-01-08 16:57

from django.db import migrations, models
import newsletter.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newsletter_email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_subscriptor', models.EmailField(max_length=255, validators=[newsletter.models.email_validation_black_list])),
            ],
        ),
    ]
