# Generated by Django 4.0.3 on 2023-07-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter_email',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
