# Generated by Django 4.0.3 on 2023-07-17 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_newsletter_email_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter_email',
            name='active',
        ),
    ]
