#ESto utilízoo para traducir os países da lista. Temos que por o _lazy porque estamos a traballar con modelos.
#Podes atopar máis info nesta páxina:
# http://djangobook.py3k.cn/chapter18/en/
from django.utils.translation import gettext_lazy as _

country_list_values = (
    ("Afghanistan",_("Afghanistan")),
    ("Albania",_("Albania")),
    ("Algeria",_("Algeria")),
    ("Andorra",_("Andorra")),
    ("Angola",_("Angola")),
    ("Antigua and Barbuda",_("Antigua and Barbuda")),
    ("Argentina",_("Argentina")),
    ("Armenia",_("Armenia")),
    ("Australia",_("Australia")),
    ("Austria",_("Austria")),
    ("Azerbaijan",_("Azerbaijan")),
    ("Bahamas",_("Bahamas")),
    ("Bahrain",_("Bahrain")),
    ("Bangladesh",_("Bangladesh")),
    ("Barbados",_("Barbados")),
    ("Belarus",_("Belarus")),
    ("Belgium",_("Belgium")),
    ("Belize",_("Belize")),
    ("Benin",_("Benin")),
    ("Bhutan",_("Bhutan")),
    ("Bolivia",_("Bolivia")),
    ("Bosnia and Herzegovina",_("Bosnia and Herzegovina")),
    ("Botswana",_("Botswana")),
    ("Brazil",_("Brazil")),
    ("Brunei",_("Brunei")),
    ("Bulgaria",_("Bulgaria")),
    ("Burkina Faso",_("Burkina Faso")),
    ("Burundi",_("Burundi")),
    ("Côte d'Ivoire",_("Côte d'Ivoire")),
    ("Cabo Verde",_("Cabo Verde")),
    ("Cambodia",_("Cambodia")),
    ("Cameroon",_("Cameroon")),
    ("Canada",_("Canada")),
    ("Central African Republic",_("Central African Republic")),
    ("Chad",_("Chad")),
    ("Chile",_("Chile")),
    ("China",_("China")),
    ("Colombia",_("Colombia")),
    ("Comoros",_("Comoros")),
    ("Congo (Congo-Brazzaville)",_("Congo (Congo-Brazzaville)")),
    ("Costa Rica",_("Costa Rica")),
    ("Croatia",_("Croatia")),
    ("Cuba",_("Cuba")),
    ("Cyprus",_("Cyprus")),
    ("Czechia (Czech Republic)",_("Czechia (Czech Republic)")),
    ("Democratic Republic of the Congo",_("Democratic Republic of the Congo")),
    ("Denmark",_("Denmark")),
    ("Djibouti",_("Djibouti")),
    ("Dominica",_("Dominica")),
    ("Dominican Republic",_("Dominican Republic")),
    ("Ecuador",_("Ecuador")),
    ("Egypt",_("Egypt")),
    ("El Salvador",_("El Salvador")),
    ("Equatorial Guinea",_("Equatorial Guinea")),
    ("Eritrea",_("Eritrea")),
    ("Estonia",_("Estonia")),
    ("Swaziland",_("Eswatini")),
    ("Ethiopia",_("Ethiopia")),
    ("Fiji",_("Fiji")),
    ("Finland",_("Finland")),
    ("France",_("France")),
    ("Gabon",_("Gabon")),
    ("Gambia",_("Gambia")),
    ("Georgia",_("Georgia")),
    ("Germany",_("Germany")),
    ("Ghana",_("Ghana")),
    ("Greece",_("Greece")),
    ("Grenada",_("Grenada")),
    ("Guatemala",_("Guatemala")),
    ("Guinea",_("Guinea")),
    ("Guinea-Bissau",_("Guinea-Bissau")),
    ("Guyana",_("Guyana")),
    ("Haiti",_("Haiti")),
    ("Holy See",_("Holy See")),
    ("Honduras",_("Honduras")),
    ("Hungary",_("Hungary")),
    ("Iceland",_("Iceland")),
    ("India",_("India")),
    ("Indonesia",_("Indonesia")),
    ("Iran",_("Iran")),
    ("Iraq",_("Iraq")),
    ("Ireland",_("Ireland")),
    ("Israel",_("Israel")),
    ("Italy",_("Italy")),
    ("Jamaica",_("Jamaica")),
    ("Japan",_("Japan")),
    ("Jordan",_("Jordan")),
    ("Kazakhstan",_("Kazakhstan")),
    ("Kenya",_("Kenya")),
    ("Kiribati",_("Kiribati")),
    ("Kuwait",_("Kuwait")),
    ("Kyrgyzstan",_("Kyrgyzstan")),
    ("Laos",_("Laos")),
    ("Latvia",_("Latvia")),
    ("Lebanon",_("Lebanon")),
    ("Lesotho",_("Lesotho")),
    ("Liberia",_("Liberia")),
    ("Libya",_("Libya")),
    ("Liechtenstein",_("Liechtenstein")),
    ("Lithuania",_("Lithuania")),
    ("Luxembourg",_("Luxembourg")),
    ("Madagascar",_("Madagascar")),
    ("Malawi",_("Malawi")),
    ("Malaysia",_("Malaysia")),
    ("Maldives",_("Maldives")),
    ("Mali",_("Mali")),
    ("Malta",_("Malta")),
    ("Marshall Islands",_("Marshall Islands")),
    ("Mauritania",_("Mauritania")),
    ("Mauritius",_("Mauritius")),
    ("Mexico",_("Mexico")),
    ("Micronesia",_("Micronesia")),
    ("Moldova",_("Moldova")),
    ("Monaco",_("Monaco")),
    ("Mongolia",_("Mongolia")),
    ("Montenegro",_("Montenegro")),
    ("Morocco",_("Morocco")),
    ("Mozambique",_("Mozambique")),
    ("Myanmar",_("Myanmar")),
    ("Namibia",_("Namibia")),
    ("Nauru",_("Nauru")),
    ("Nepal",_("Nepal")),
    ("Netherlands",_("Netherlands")),
    ("New Zealand",_("New Zealand")),
    ("Nicaragua",_("Nicaragua")),
    ("Niger",_("Niger")),
    ("Nigeria",_("Nigeria")),
    ("North Korea",_("North Korea")),
    ("Macedonia",_("Macedonia")),
    ("Norway",_("Norway")),
    ("Oman",_("Oman")),
    ("Pakistan",_("Pakistan")),
    ("Palau",_("Palau")),
    ("Palestine",_("Palestine")),
    ("Panama",_("Panama")),
    ("Papua New Guinea",_("Papua New Guinea")),
    ("Paraguay",_("Paraguay")),
    ("Peru",_("Peru")),
    ("Philippines",_("Philippines")),
    ("Poland",_("Poland")),
    ("Portugal",_("Portugal")),
    ("Qatar",_("Qatar")),
    ("Romania",_("Romania")),
    ("Russia",_("Russia")),
    ("Rwanda",_("Rwanda")),
    ("Saint Lucia",_("Saint Lucia")),
    ("Samoa",_("Samoa")),
    ("San Marino",_("San Marino")),
    ("Sao Tome and Principe",_("Sao Tome and Principe")),
    ("Saudi Arabia",_("Saudi Arabia")),
    ("Senegal",_("Senegal")),
    ("Serbia",_("Serbia")),
    ("Seychelles",_("Seychelles")),
    ("Sierra Leone",_("Sierra Leone")),
    ("Singapore",_("Singapore")),
    ("Slovakia",_("Slovakia")),
    ("Slovenia",_("Slovenia")),
    ("Solomon Islands",_("Solomon Islands")),
    ("Somalia",_("Somalia")),
    ("South Africa",_("South Africa")),
    ("South Korea",_("South Korea")),
    ("South Sudan",_("South Sudan")),
    ("Spain",_("Spain")),
    ("Sri Lanka",_("Sri Lanka")),
    ("Sudan",_("Sudan")),
    ("Suriname",_("Suriname")),
    ("Sweden",_("Sweden")),
    ("Switzerland",_("Switzerland")),
    ("Syria",_("Syria")),
    ("Tajikistan",_("Tajikistan")),
    ("Tanzania",_("Tanzania")),
    ("Thailand",_("Thailand")),
    ("Timor-Leste",_("Timor-Leste")),
    ("Togo",_("Togo")),
    ("Tonga",_("Tonga")),
    ("Trinidad and Tobago",_("Trinidad and Tobago")),
    ("Tunisia",_("Tunisia")),
    ("Turkey",_("Turkey")),
    ("Turkmenistan",_("Turkmenistan")),
    ("Tuvalu",_("Tuvalu")),
    ("Uganda",_("Uganda")),
    ("Ukraine",_("Ukraine")),
    ("United Arab Emirates",_("United Arab Emirates")),
    ("United Kingdom",_("United Kingdom")),
    ("United States of America",_("United States of America")),
    ("Uruguay",_("Uruguay")),
    ("Uzbekistan",_("Uzbekistan")),
    ("Vanuatu",_("Vanuatu")),
    ("Venezuela",_("Venezuela")),
    ("Vietnam",_("Vietnam")),
    ("Yemen",_("Yemen")),
    ("Zambia",_("Zambia")),
    ("Zimbabwe",_("Zimbabwe"))
)




