# Generated by Django 4.1.2 on 2022-12-11 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rider_model',
            name='bicycle_brand',
        ),
        migrations.RemoveField(
            model_name='rider_model',
            name='bicycle_model',
        ),
        migrations.RemoveField(
            model_name='rider_model',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='rider_model',
            name='country',
        ),
        migrations.RemoveField(
            model_name='rider_model',
            name='name',
        ),
        migrations.RemoveField(
            model_name='rider_model',
            name='navigation_system',
        ),
        migrations.RemoveField(
            model_name='rider_model',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='rider_model',
            name='region',
        ),
        migrations.RemoveField(
            model_name='rider_model',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='rider_model',
            name='telephone',
        ),
    ]
