# Generated by Django 4.0.3 on 2023-07-03 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_rider_model_bicycle_brand_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rider_model',
            new_name='sign_in_model',
        ),
    ]
