# Generated by Django 4.0.3 on 2023-07-04 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_rename_rider_model_sign_in_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sign_in_model',
        ),
    ]
