# Generated by Django 4.0.3 on 2023-07-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
